### ISSUE TITLE
/reloadAdminTable crashes server

### ISSUE THREAD

**Issue by Gene64** [SWG-Source/src#2]
Using the /reloadAdminTable in-game crashes the server.

**Comment by AlecH92** [comment]
The user you added needs to have logged in and created a character for their stationid to be created in the database. Otherwise the reload command will indeed crash the server.

**Comment by Gene64** [comment]
Hello @AlecH92, the datatable was reloaded after the person had already logged in with a character from the account.

Though, reloading the admin datatable doesn't involve the database, so that shouldn't matter anyways.

**Comment by AconiteGodOfSWG** [comment]
@AlecH92 was this fixed with your change in a9ffeca8c3f1e653add9766ceaec5bd00ff585e6 and 625e4d168f24aa2590c6fe4ac78e7a1164e5b03f?

**Comment by AlecH92** [comment]
it _should_ be, yes. I didn't test on a Source VM though.

**Comment by Cekis** [comment]
Tested - this is fixed.
