### ISSUE TITLE
Error: "Failed to commit xxxxx bytes this frame..."

### ISSUE THREAD

**Issue by Gene64** [SWG-Source/src#4]
![image](https://user-images.githubusercontent.com/18705050/57201110-4e247100-6f62-11e9-868b-aa757b8e75bf.png)

The bytes just keep increasing until the server crashes.

It only happens after the server has been up for a while.

**Comment by Tekaoh** [comment]
Have you tried just recompiling the src?

**Comment by Gene64** [comment]
> Have you tried just recompiling the src?

Yes, this happens on all versions, darth had this issue on Stella Bellum's test center as well.

**Comment by Tekaoh** [comment]
Hmm. This happens for you all the time? I've never seen it. I wonder what's different about your configuration than mine.

**Comment by Gene64** [comment]
> Hmm. This happens for you all the time? I've never seen it. I wonder what's different about your configuration than mine.

I have multi-server enabled and it happens after the server is up for about a week.

**Comment by Tekaoh** [comment]
Oh well multi-server is a pretty important detail lol. That's a whole other animal. I've never tried using multi-server

**Comment by swgresurgence** [comment]
I've been told that this is an issue with the Operating System, and that in order to fix it, would require an engine re-write.  Anyone agree?

**Comment by Tekaoh** [comment]
Multi-server isn't even currently on the radar for this project, so I'm just going to close this out for now.
