### ISSUE TITLE
Idle Logout Timer Issue

### ISSUE THREAD

**Issue by IrishDarkshadow** [SWG-Source/src#6]
Reported by Nifenap via Discord:

really weird stuff going on with the idle logout time... did some further testing... 

yesterday, before going to bed I set up the server with timeout set to 900s (which should result in 15 minutes after going auto afk after 10 minutes). I let the PC run and had two clients logged in. one with anti afk script (simply spamming an emoute every minute) and one without. 
This morning both were still logged in. 

next try was setting the timer variable to 60 - which shouldLD the char 60s after the AFK is set. well - it doesn't. The char went LD after 5 Minutes (300s). 

next try was the default setting from the GIT repo again (300). should be 5 Minutes. But it's about 15 Minutes. 

next try was setting the variable 600 - which seem to have same effect as 900 - no LD. 

./ponder

I also tried to dig through the C++ files which seem to be related to the variable. But I'm not really that C++ guy. I did not find a calculation or something which could explain this strange behaviour. shrug 

For now it seems to work with my 900 setting as "no LD" , but it's something which is not working as intended, I'd say.

**Comment by Cekis** [comment]
After testing this and putting it through some trial and error, it seems to be working as expected.
